In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/interim/04-default_credit_clean.csv")

In [3]:
df.columns

Index(['ID', 'LIMIT_BAL', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month',
       'SEX_2', 'EDUCATION_1', 'EDUCATION_2', 'EDUCATION_3', 'EDUCATION_4',
       'EDUCATION_5', 'EDUCATION_6', 'MARRIAGE_1', 'MARRIAGE_2', 'MARRIAGE_3'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   AGE                         30000 non-null  float64
 3   PAY_0                       30000 non-null  float64
 4   PAY_2                       30000 non-null  float64
 5   PAY_3                       30000 non-null  float64
 6   PAY_4                       30000 non-null  float64
 7   PAY_5                       30000 non-null  float64
 8   PAY_6                       30000 non-null  float64
 9   BILL_AMT1                   30000 non-null  float64
 10  BILL_AMT2                   30000 non-null  float64
 11  BILL_AMT3                   30000 non-null  float64
 12  BILL_AMT4                   30000 non-null  float64
 13  BILL_AMT5                   30000 non-null  float64
 14  BILL_AMT6                   30000 non-null  float64
 15  PAY_AMT1                    30000 non-null  int64
 16  PAY_AMT2                    30000 non-null  float64
 17  PAY_AMT3                    30000 non-null  float64
 18  PAY_AMT4                    30000 non-null  float64
 19  PAY_AMT5                    30000 non-null  int64
 20  PAY_AMT6                    30000 non-null  float64
 21  default payment next month  30000 non-null  int64
 22  SEX_2                       30000 non-null  bool
 23  EDUCATION_1                 30000 non-null  bool
 24  EDUCATION_2                 30000 non-null  bool
 25  EDUCATION_3                 30000 non-null  bool
 26  EDUCATION_4                 30000 non-null  bool
 27  EDUCATION_5                 30000 non-null  bool
 28  EDUCATION_6                 30000 non-null  bool
 29  MARRIAGE_1                  30000 non-null  bool
 30  MARRIAGE_2                  30000 non-null  bool
 31  MARRIAGE_3                  30000 non-null  bool
dtypes: bool(10), float64(17), int64(5)
memory usage: 5.3 MB

In [5]:
df.head()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,SEX_2,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,EDUCATION_5,EDUCATION_6,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3
0,1,20000,24.0,1.5,1.5,-1.0,-1.0,-2.0,-2.0,3913.0,...,True,False,True,False,False,False,False,True,False,False
1,2,120000,26.0,-1.0,1.5,0.0,0.0,0.0,1.5,2682.0,...,True,False,True,False,False,False,False,False,True,False
2,3,90000,34.0,0.0,0.0,0.0,0.0,0.0,0.0,29239.0,...,True,False,True,False,False,False,False,False,True,False
3,4,50000,37.0,0.0,0.0,0.0,0.0,0.0,0.0,46990.0,...,True,False,True,False,False,False,False,True,False,False
4,5,50000,57.0,-1.0,0.0,-1.0,0.0,0.0,0.0,8617.0,...,False,False,True,False,False,False,False,True,False,False

In [6]:
df.describe()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,166967.489333,35.449467,-0.094033,-0.232367,-0.259683,-0.303967,-0.339300,-0.363717,44293.480167,...,36551.073642,33754.151258,32595.088604,3496.730800,3422.306967,3035.817900,2718.296075,2731.547167,2714.437875,0.221200
std,8660.398374,128013.394323,9.106024,0.951983,0.991794,0.995493,0.969589,0.947772,0.970910,51294.870270,...,42751.481350,39896.030557,39367.735129,3492.742781,3532.819886,3355.632738,3073.301491,3094.091228,3131.180741,0.415062
min,1.000000,10000.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-91739.625000,...,-75942.125000,-70878.250000,-70657.375000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3558.750000,...,2326.750000,1763.000000,1256.000000,1000.000000,833.000000,390.000000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22381.500000,...,19052.000000,18104.500000,17071.000000,2100.000000,2009.000000,1800.000000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67091.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5000.000000,4505.000000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,525000.000000,60.500000,1.500000,1.500000,1.500000,1.500000,1.500000,1.500000,162389.375000,...,132774.875000,122831.750000,121111.625000,11015.000000,11250.500000,10677.500000,9589.125000,9700.000000,9823.375000,1.000000

In [7]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
SEX_2                         0
EDUCATION_1                   0
EDUCATION_2                   0
EDUCATION_3                   0
EDUCATION_4                   0
EDUCATION_5                   0
EDUCATION_6                   0
MARRIAGE_1                    0
MARRIAGE_2                    0
MARRIAGE_3                    0
dtype: int64

In [8]:
df["default payment next month"].value_counts()

default payment next month
0    23364
1     6636
Name: count, dtype: int64

# Ratio de utilizacion de credito

avg_bill: Promedio de deuda mensual del cliente

credit_utilization:
Mide qué porcentaje del crédito disponible está usando el cliente.

0.1 → usa poco crédito

0.5 → uso moderado

0.9+ → alto riesgo de sobreendeudamiento

In [9]:
#Ratio de utilizacion de credito
df["avg_bill"] = df[[f"BILL_AMT{i}" for i in range(1,7)]].mean(axis=1)

df["credit_utilization"] = df["avg_bill"] / df["LIMIT_BAL"]

# Ratio de pago
avg_pay: Promedio de pagos mensuales del cliente.

payment_ratio: Cuanto paga vs cuanto debe.

In [10]:
# Ratio de pago
df["avg_pay"] = df[[f"PAY_AMT{i}" for i in range(1,7)]].mean(axis=1)

df["payment_ratio"] = df["avg_pay"] / (df["avg_bill"] + 1)

# Riesgo de impago
late_payments: cuantos meses el cliente se retraso en pagos

In [12]:
# Riesgo de impago
pay_cols = [col for col in df.columns if "PAY_" in col and col != "PAY_0"]
df["late_payments"] = df[pay_cols].apply(lambda x: (x > 0).sum(), axis=1)

bill_trend: Cambio de deuda entre el inicio y el final del periodo observado

Positivo deuda aumento y negativo la deuda disminuyo

In [13]:
# Cambio de deuda
df["bill_trend"] = df["BILL_AMT6"] - df["BILL_AMT1"]

# Evolución de los pagos del cliente en el tiempo

In [14]:
# Cambio de pagos 
df["pay_trend"] = df["PAY_AMT6"] - df["PAY_AMT1"]

In [15]:
# Edad en grupos 
df["age_group"] = pd.cut(df["AGE"], bins=[0,25,35,50,100], labels=["young","adult","middle","senior"])

In [16]:
# Credito por niveles
df["credit_level"] = pd.cut(df["LIMIT_BAL"], bins=5)

# Score de riesgo financiero simple

LIMIT_BAL: Cuanto credito tiene el cliente

late_payments: Cuantas veces se atraso

In [17]:
# Riesgo financiero
df["risk_score"] = df["LIMIT_BAL"] * df["late_payments"]

# Capacidad de pago del cliente

In [18]:
# Capacidad de pago
df["ability_to_pay"] = df["PAY_AMT1"] + df["PAY_AMT2"] + df["PAY_AMT3"]

Transformacion de linea de credito evita valores grandes

In [21]:
df["log_limit"] = np.log1p(df["LIMIT_BAL"])
df["log_avg_bill"] = np.log1p(df["avg_bill"].clip(lower=0))

# Eliminacion por correlacion

In [39]:
corr = df.corr(numeric_only=True)

In [29]:
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

In [30]:
to_drop = [col for col in upper.columns if any(upper[col].abs() > 0.95)]
to_drop

['MARRIAGE_2', 'avg_bill']

In [32]:
#Se eliminaron variables con correlación mayor a 0.95 para reducir multicolinealidad y mejorar estabilidad del modelo.

In [31]:
df_reduced = df.drop(columns=to_drop)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   AGE                         30000 non-null  float64
 3   PAY_0                       30000 non-null  float64
 4   PAY_2                       30000 non-null  float64
 5   PAY_3                       30000 non-null  float64
 6   PAY_4                       30000 non-null  float64
 7   PAY_5                       30000 non-null  float64
 8   PAY_6                       30000 non-null  float64
 9   BILL_AMT1                   30000 non-null  float64
 10  BILL_AMT2                   30000 non-null  float64
 11  BILL_AMT3                   30000 non-null  float64
 12  BILL_AMT4                   30000 non-null  float64
 13  BILL_AMT5                   30000 non-null  float64
 14  BILL_AMT6                   30000 non-null  float64
 15  PAY_AMT1                    30000 non-null  int64
 16  PAY_AMT2                    30000 non-null  float64
 17  PAY_AMT3                    30000 non-null  float64
 18  PAY_AMT4                    30000 non-null  float64
 19  PAY_AMT5                    30000 non-null  int64
 20  PAY_AMT6                    30000 non-null  float64
 21  default payment next month  30000 non-null  int64
 22  SEX_2                       30000 non-null  bool
 23  EDUCATION_1                 30000 non-null  bool
 24  EDUCATION_2                 30000 non-null  bool
 25  EDUCATION_3                 30000 non-null  bool
 26  EDUCATION_4                 30000 non-null  bool
 27  EDUCATION_5                 30000 non-null  bool
 28  EDUCATION_6                 30000 non-null  bool
 29  MARRIAGE_1                  30000 non-null  bool
 30  MARRIAGE_2                  30000 non-null  bool
 31  MARRIAGE_3                  30000 non-null  bool
 32  avg_bill                    30000 non-null  float64
 33  credit_utilization          30000 non-null  float64
 34  avg_pay                     30000 non-null  float64
 35  payment_ratio               29998 non-null  float64
 36  late_payments               30000 non-null  int64
 37  bill_trend                  30000 non-null  float64
 38  pay_trend                   30000 non-null  float64
 39  age_group                   30000 non-null  category
 40  credit_level                30000 non-null  category
 41  risk_score                  30000 non-null  int64
 42  ability_to_pay              30000 non-null  float64
 43  log_limit                   30000 non-null  float64
 44  log_avg_bill                30000 non-null  float64
dtypes: bool(10), category(2), float64(26), int64(7)
memory usage: 7.9 MB

In [34]:
df["payment_ratio"] = df["payment_ratio"].fillna(df["payment_ratio"].median())

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   AGE                         30000 non-null  float64
 3   PAY_0                       30000 non-null  float64
 4   PAY_2                       30000 non-null  float64
 5   PAY_3                       30000 non-null  float64
 6   PAY_4                       30000 non-null  float64
 7   PAY_5                       30000 non-null  float64
 8   PAY_6                       30000 non-null  float64
 9   BILL_AMT1                   30000 non-null  float64
 10  BILL_AMT2                   30000 non-null  float64
 11  BILL_AMT3                   30000 non-null  float64
 12  BILL_AMT4                   30000 non-null  float64
 13  BILL_AMT5                   30000 non-null  float64
 14  BILL_AMT6                   30000 non-null  float64
 15  PAY_AMT1                    30000 non-null  int64
 16  PAY_AMT2                    30000 non-null  float64
 17  PAY_AMT3                    30000 non-null  float64
 18  PAY_AMT4                    30000 non-null  float64
 19  PAY_AMT5                    30000 non-null  int64
 20  PAY_AMT6                    30000 non-null  float64
 21  default payment next month  30000 non-null  int64
 22  SEX_2                       30000 non-null  bool
 23  EDUCATION_1                 30000 non-null  bool
 24  EDUCATION_2                 30000 non-null  bool
 25  EDUCATION_3                 30000 non-null  bool
 26  EDUCATION_4                 30000 non-null  bool
 27  EDUCATION_5                 30000 non-null  bool
 28  EDUCATION_6                 30000 non-null  bool
 29  MARRIAGE_1                  30000 non-null  bool
 30  MARRIAGE_2                  30000 non-null  bool
 31  MARRIAGE_3                  30000 non-null  bool
 32  avg_bill                    30000 non-null  float64
 33  credit_utilization          30000 non-null  float64
 34  avg_pay                     30000 non-null  float64
 35  payment_ratio               30000 non-null  float64
 36  late_payments               30000 non-null  int64
 37  bill_trend                  30000 non-null  float64
 38  pay_trend                   30000 non-null  float64
 39  age_group                   30000 non-null  category
 40  credit_level                30000 non-null  category
 41  risk_score                  30000 non-null  int64
 42  ability_to_pay              30000 non-null  float64
 43  log_limit                   30000 non-null  float64
 44  log_avg_bill                30000 non-null  float64
dtypes: bool(10), category(2), float64(26), int64(7)
memory usage: 7.9 MB

In [43]:
df.to_csv("../data/processed/04_default_credit_features.csv", index=False)